services:
  coredns:
    image: docker.io/coredns/coredns
    command: -conf /etc/coredns/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./coredns:/etc/coredns:ro
    environment:
      - NC_IP=${NC_IP}
      - NC_HOST=${NC_HOST}
      - SY_IP=${SY_IP}
      - SY_HOST=${SY_HOST}
