ServerName ${SW_HOST}

# OpenID Connect Configuration
OIDCProviderMetadataURL https://${KC_HOST}/realms/${KC_REALM}/.well-known/openid-configuration
OIDCClientID ${SW_CLIENT_ID}
OIDCClientSecret ${SW_CLIENT_SECRET}
OIDCProviderTokenEndpointAuth client_secret_basic
OIDCRedirectURI https://${SW_HOST}/users/callback
OIDCCryptoPassphrase 46272d54-1b7c-4bdf-bbb1-a67dd1c31200
OIDCSessionMaxDuration 15

# Protect all paths by default
<Location />
    AuthType openid-connect
    Require valid-user
</Location>

# Logout Configuration
<Location /logout>
    AuthType openid-connect
    Require valid-user
    Redirect 302 /logout https://${KC_HOST}/realms/${KC_REALM}/protocol/openid-connect/logout?post_logout_redirect_uri=https://${SW_HOST}&client_id=${SW_CLIENT_ID}
</Location>